spring.application.name=dsa-system

# 服务器配置
server.port=8082

# 数据库连接配置
spring.datasource.url=jdbc:mysql://gateway01.ap-northeast-1.prod.aws.tidbcloud.com:4000/driving_school_db?useSSL=true&serverTimezone=UTC
spring.datasource.username=4X5dX9YV3TLV1iy.root
spring.datasource.password=LqKcL4mKJ6tOImzQ
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# MyBatis Plus Configuration
mybatis-plus.mapper-locations=classpath:mapper/*.xml
mybatis-plus.type-aliases-package=com.djxlzk.dsasystem.entity
mybatis-plus.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl
mybatis-plus.configuration.map-underscore-to-camel-case=true
